sudo: required 
services:
  - docker 

before_install:
  - docker build -t khalil/fib-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true khalil/fib-docker npm test -- --coverage

after_success:
  - docker build -t khalil/fib-client ./client
  - docker build -t khalil/fib-nginx ./nginx 
  - docker build -t khalil/fib-server ./server 
  - docker build -t khalil/fib-worker ./worker 
# log dokcer cli
  - echo "$doc_pass" | docker login -u "$doc_id" -- password-stdin
# push to doc hub
  - docker push khalil/fib-client 
  - docker push khalil/fib-nginx
  - docker push khalil/fib-server
  - docker push khalil/fib-worker

#deploy:
#  provider: elasticbeanstalk
#  region: "eu-west-3"
#  app: docker-travis
#  env: "dockertravis-env"
#  bucket_name: "elasticbeanstalk-eu-west-3-907076315131"
 # bucket_path: "docker-travis"
#on:
#  branch: master    
#access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: "$AWS_SECRET_KEY"